# Generated by Django 4.2.7 on 2023-11-14 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0002_rename_new_adstars_student_adstars_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='adcoins',
            new_name='adcoins_change',
        ),
    ]
