# Generated by Django 4.2.7 on 2023-11-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0003_rename_adcoins_history_adcoins_change'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_no', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('pdf_link', models.URLField()),
            ],
        ),
    ]
