# Generated by Django 4.2.7 on 2023-11-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0004_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='pdf_link',
        ),
        migrations.AddField(
            model_name='lesson',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='reference_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
