# Generated by Django 4.2.7 on 2023-11-28 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0005_remove_lesson_pdf_link_lesson_pdf_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('attendance_time', models.TimeField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranking.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranking.student')),
            ],
        ),
    ]
