# Generated by Django 4.2.7 on 2023-12-02 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0007_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_no',
            field=models.IntegerField(unique=True),
        ),
    ]
